openapi: 3.0.0
info:
  title: Swagger test
servers:
  - url: http://localhost:3000

paths:
  /status:
    get: 
      tags:
        - Status
      summary: 'Check server status'
      responses:
        200:
          description: Server is running
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
  /login: 
    post:
      tags:
        - Auth
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginPayload'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  expiresIn:
                    type: string
                  refreshToken:
                    type: string
  /me: 
    get:
      tags:
        - Auth
      summary: get user
      security:
        - bearerAuth: []
      responses:
        200:
          description: 'get user info'
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id: 
                    type: string
                  email:
                    type: string
                    format: email
                  password:
                    type: string



components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      format: JWT

  schemas:
    Message:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    LoginPayload:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
